
content = open('gitmanager.py', 'r', encoding='utf-8').read()
orig_len = len(content)

# ── 1) Fix search_var trace guard ──────────────────────────────────────────
old = '        self.search_var.trace_add("write", lambda *_: self._filter_repos())'
new = ('        self.search_var.trace_add("write", lambda *_: self._filter_repos()\n'
       '                                  if hasattr(self, "repo_tree") else None)')
assert old in content, "MISS-1"
content = content.replace(old, new, 1)

# ── 2) Add working_tree tag after column definitions ────────────────────────
old = '        ys = ttk.Scrollbar(left_frame, orient="vertical",   command=self.log_tree.yview)'
new = ('        self.log_tree.tag_configure("working_tree", foreground="#fbbf24",\n'
       '                                    font=("Consolas", 10, "bold"))\n\n'
       '        ys = ttk.Scrollbar(left_frame, orient="vertical",   command=self.log_tree.yview)')
assert old in content, "MISS-2"
content = content.replace(old, new, 1)

# ── 3) Insert staging panel UI before vertical paned window ────────────────
PANE_ANCHOR = ('        # vertical split inside right panel: file list (top) + diff (bottom)\n'
               '        v_pane = ttk.PanedWindow(right_frame, orient="vertical")\n'
               '        v_pane.pack(fill="both", expand=True)\n'
               '\n'
               '        # \u2500\u2500 top: files changed in the commit\n'
               '        files_frame = ttk.Frame(v_pane)')
STAGING_UI = (
    '        # staging panel (hidden by default)\n'
    '        self._staging_panel = tk.Frame(right_frame, bg="#252638")\n'
    '\n'
    '        _stg_hdr = tk.Frame(self._staging_panel, bg="#2d2f45", height=28)\n'
    '        _stg_hdr.pack(fill="x")\n'
    '        _stg_hdr.pack_propagate(False)\n'
    '        tk.Label(_stg_hdr, text="  Stage files for commit",\n'
    '                 bg="#2d2f45", fg="#fbbf24", font=("Consolas", 10, "bold"),\n'
    '                 anchor="w").pack(side="left", padx=6, pady=4)\n'
    '\n'
    '        _stg_lo = tk.Frame(self._staging_panel, bg="#252638")\n'
    '        _stg_lo.pack(fill="both", expand=True, padx=6, pady=4)\n'
    '        _stg_cv = tk.Canvas(_stg_lo, bg="#252638", bd=0, highlightthickness=0)\n'
    '        _stg_sb = ttk.Scrollbar(_stg_lo, orient="vertical", command=_stg_cv.yview)\n'
    '        self._stg_inner = tk.Frame(_stg_cv, bg="#252638")\n'
    '        self._stg_inner.bind("<Configure>",\n'
    '            lambda e: _stg_cv.configure(scrollregion=_stg_cv.bbox("all")))\n'
    '        _stg_cv.create_window((0, 0), window=self._stg_inner, anchor="nw")\n'
    '        _stg_cv.configure(yscrollcommand=_stg_sb.set)\n'
    '        _stg_cv.pack(side="left", fill="both", expand=True)\n'
    '        _stg_sb.pack(side="right", fill="y")\n'
    '        _stg_cv.bind("<MouseWheel>",\n'
    '                     lambda e: _stg_cv.yview_scroll(-1*(e.delta//120), "units"))\n'
    '        self._stg_canvas = _stg_cv\n'
    '\n'
    '        _stg_br = tk.Frame(self._staging_panel, bg="#252638")\n'
    '        _stg_br.pack(fill="x", padx=6, pady=(0, 4))\n'
    '        ttk.Button(_stg_br, text="Select All",\n'
    '                   command=self._stage_select_all).pack(side="left", padx=2)\n'
    '        ttk.Button(_stg_br, text="Select None",\n'
    '                   command=self._stage_select_none).pack(side="left", padx=2)\n'
    '\n'
    '        _stg_mf = tk.Frame(self._staging_panel, bg="#252638")\n'
    '        _stg_mf.pack(fill="x", padx=6, pady=(0, 6))\n'
    '        tk.Label(_stg_mf, text="Commit message:", bg="#252638", fg="#9496b0",\n'
    '                 font=("Consolas", 9), anchor="w").pack(anchor="w")\n'
    '        self._commit_msg_text = tk.Text(_stg_mf, bg="#2d2f45", fg="#e2e4f0",\n'
    '                                        font=("Consolas", 9), relief="flat",\n'
    '                                        height=3, insertbackground="#e2e4f0", bd=4)\n'
    '        self._commit_msg_text.pack(fill="x", pady=(2, 4))\n'
    '        ttk.Button(_stg_mf, text="Commit", command=self._do_commit,\n'
    '                   style="Accent.TButton").pack(anchor="e")\n'
    '\n'
    '        self._stg_check_vars = []  # list of (BooleanVar, status, filepath)\n'
    '\n'
)
assert PANE_ANCHOR in content, "MISS-3"
content = content.replace(PANE_ANCHOR, STAGING_UI + PANE_ANCHOR, 1)

# ── 4) Add ?? tag to commit_files_tree ────────────────────────────────────
old = ('        self.commit_files_tree.tag_configure("C",  foreground=BLUE)\n'
       '\n'
       '        cfs_sc')
new = ('        self.commit_files_tree.tag_configure("C",  foreground=BLUE)\n'
       '        self.commit_files_tree.tag_configure("??", foreground=FG2)\n'
       '\n'
       '        cfs_sc')
assert old in content, "MISS-4"
content = content.replace(old, new, 1)

# ── 5) Add working tree row in _populate_tabs ─────────────────────────────
old = ('    def _populate_tabs(self, commits, changes, branches):\n'
       '        for item in self.log_tree.get_children():\n'
       '            self.log_tree.delete(item)\n'
       '        for c in commits:')
new = ('    def _populate_tabs(self, commits, changes, branches):\n'
       '        for item in self.log_tree.get_children():\n'
       '            self.log_tree.delete(item)\n'
       '\n'
       '        _n = len(changes)\n'
       '        _wt = ("Working Tree / Index  (" + str(_n) + " changed)"\n'
       '               if _n else "Working Tree / Index  (clean)")\n'
       '        self.log_tree.insert("", "end", iid="__working_tree__",\n'
       '                             values=("\u25cf", "now", _wt, ""),\n'
       '                             tags=("working_tree",) if _n else ())\n'
       '\n'
       '        for c in commits:')
assert old in content, "MISS-5"
content = content.replace(old, new, 1)

# ── 6) Replace _on_commit_select ──────────────────────────────────────────
old = ('    def _on_commit_select(self, event=None):\n'
       '        sel = self.log_tree.selection()\n'
       '        if not sel or not self.selected_repo:\n'
       '            return\n'
       '        commit_hash = sel[0]   # iid == full hash\n'
       '        self._selected_commit_hash = commit_hash\n'
       '        short = commit_hash[:8]\n'
       '\n'
       '        # update header label\n'
       '        values = self.log_tree.item(commit_hash, "values")\n'
       '        msg    = values[2] if len(values) > 2 else ""\n'
       '        self.commit_detail_label.config(\n'
       '            text=f"  \u2299 {short}  \u2014  {msg[:80]}", fg=ACCENT\n'
       '        )\n'
       '\n'
       '        # clear file list and diff\n'
       '        for item in self.commit_files_tree.get_children():\n'
       '            self.commit_files_tree.delete(item)\n'
       '        self._clear_commit_diff()\n'
       '\n'
       '        # load file list in background\n'
       '        threading.Thread(\n'
       '            target=self._bg_load_commit_files,\n'
       '            args=(self.selected_repo["path"], commit_hash),\n'
       '            daemon=True\n'
       '        ).start()')
new = ('    def _on_commit_select(self, event=None):\n'
       '        sel = self.log_tree.selection()\n'
       '        if not sel or not self.selected_repo:\n'
       '            return\n'
       '        commit_hash = sel[0]\n'
       '\n'
       '        if commit_hash == "__working_tree__":\n'
       '            self._selected_commit_hash = None\n'
       '            self.commit_detail_label.config(\n'
       '                text="  \u25cf Working Tree / Index \u2014 stage files and commit",\n'
       '                fg=YELLOW\n'
       '            )\n'
       '            self._show_staging_panel()\n'
       '            return\n'
       '\n'
       '        self._staging_panel.pack_forget()\n'
       '        self._selected_commit_hash = commit_hash\n'
       '        short = commit_hash[:8]\n'
       '\n'
       '        values = self.log_tree.item(commit_hash, "values")\n'
       '        msg = values[2] if len(values) > 2 else ""\n'
       '        self.commit_detail_label.config(\n'
       '            text="  \u2299 " + short + "  \u2014  " + msg[:80], fg=ACCENT\n'
       '        )\n'
       '\n'
       '        for item in self.commit_files_tree.get_children():\n'
       '            self.commit_files_tree.delete(item)\n'
       '        self._clear_commit_diff()\n'
       '\n'
       '        threading.Thread(\n'
       '            target=self._bg_load_commit_files,\n'
       '            args=(self.selected_repo["path"], commit_hash),\n'
       '            daemon=True\n'
       '        ).start()\n'
       '\n'
       '    # \u2500\u2500 Staging panel helpers \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n'
       '\n'
       '    def _show_staging_panel(self):\n'
       '        if not self.selected_repo:\n'
       '            return\n'
       '        path = self.selected_repo["path"]\n'
       '        rc, out, _ = run_git(["status", "--porcelain"], path)\n'
       '        changes = []\n'
       '        if rc == 0:\n'
       '            for line in out.splitlines():\n'
       '                if line:\n'
       '                    st = line[:2].strip() or "?"\n'
       '                    fn = line[3:].strip()\n'
       '                    changes.append((st, fn))\n'
       '\n'
       '        for w in self._stg_inner.winfo_children():\n'
       '            w.destroy()\n'
       '        self._stg_check_vars.clear()\n'
       '\n'
       '        for st, fn in changes:\n'
       '            var = tk.BooleanVar(value=True)\n'
       '            color = {"M": YELLOW, "A": GREEN, "D": RED, "??": FG2}.get(st, FG)\n'
       '            row = tk.Frame(self._stg_inner, bg=BG2)\n'
       '            row.pack(fill="x", pady=1)\n'
       '            tk.Checkbutton(row, variable=var, bg=BG2, fg=FG,\n'
       '                           activebackground=BG2, selectcolor=BG3,\n'
       '                           relief="flat").pack(side="left")\n'
       '            tk.Label(row, text=(st + "  " + fn), bg=BG2, fg=color,\n'
       '                     font=FONT_SM, anchor="w").pack(side="left")\n'
       '            self._stg_check_vars.append((var, st, fn))\n'
       '\n'
       '        self._stg_canvas.update_idletasks()\n'
       '        self._stg_canvas.configure(\n'
       '            scrollregion=self._stg_canvas.bbox("all"))\n'
       '        self._staging_panel.pack(fill="both", expand=False,\n'
       '                                 before=self.commit_files_tree.master.master)\n'
       '        for item in self.commit_files_tree.get_children():\n'
       '            self.commit_files_tree.delete(item)\n'
       '        self._clear_commit_diff()\n'
       '\n'
       '    def _stage_select_all(self):\n'
       '        for var, _, _ in self._stg_check_vars:\n'
       '            var.set(True)\n'
       '\n'
       '    def _stage_select_none(self):\n'
       '        for var, _, _ in self._stg_check_vars:\n'
       '            var.set(False)\n'
       '\n'
       '    def _do_commit(self):\n'
       '        if not self.selected_repo:\n'
       '            return\n'
       '        msg = self._commit_msg_text.get("1.0", "end").strip()\n'
       '        if not msg:\n'
       '            messagebox.showwarning("Commit", "Please enter a commit message.")\n'
       '            return\n'
       '        selected = [(st, fn) for var, st, fn in self._stg_check_vars\n'
       '                    if var.get()]\n'
       '        if not selected:\n'
       '            messagebox.showwarning("Commit", "No files selected for commit.")\n'
       '            return\n'
       '        path = self.selected_repo["path"]\n'
       '\n'
       '        def _bg():\n'
       '            errors = []\n'
       '            for st, fn in selected:\n'
       '                rc_a, o_a, e_a = run_git(\n'
       '                    ["add", "--force", "--", fn], path)\n'
       '                if rc_a != 0:\n'
       '                    errors.append(\n'
       '                        "git add \'" + fn + "\': " + (e_a or o_a))\n'
       '            if errors:\n'
       '                emsg = "\\n".join(errors)\n'
       '                self.after(0, self._log,\n'
       '                           "git add failed: " + emsg, "error")\n'
       '                self.after(0, messagebox.showerror,\n'
       '                           "git add failed", emsg)\n'
       '                return\n'
       '            rc, out, err = run_git(["commit", "-m", msg], path)\n'
       '            if rc == 0:\n'
       '                self.after(0, self._log,\n'
       '                           "Committed: " + msg[:60], "success")\n'
       '                self.after(0, self._commit_msg_text.delete,\n'
       '                           "1.0", "end")\n'
       '                self.after(0, self._staging_panel.pack_forget)\n'
       '                self.after(0, self._load_detail_tabs)\n'
       '            else:\n'
       '                full = err or out or "unknown error"\n'
       '                self.after(0, self._log,\n'
       '                           "Commit failed: " + full, "error")\n'
       '                self.after(0, messagebox.showerror,\n'
       '                           "Commit failed", full)\n'
       '\n'
       '        threading.Thread(target=_bg, daemon=True).start()')
assert old in content, "MISS-6"
content = content.replace(old, new, 1)

open('gitmanager.py', 'w', encoding='utf-8').write(content)
print("All patches applied. Lines:", content.count('\n'))
